export const students = [
  {
    no: 1,
    studentId: "SV001",
    name: "Nguyễn Văn A",
    dob: "1999-03-15",
    faculty: "Công nghệ thông tin",
    major: "Khoa học máy tính",
    degreeClassification: "Giỏi",
    modeOfStudy: "Chính quy",
    yearGraduation: 2021,
    dateOfIssue: "2021-08-15",
    serialNumber: "SN001",
    referenceNumber: "REF001",
  },
  {
    no: 2,
    studentId: "SV002",
    name: "Trần Thị B",
    dob: "1998-11-22",
    faculty: "Kinh tế",
    major: "Quản trị kinh doanh",
    degreeClassification: "Khá",
    modeOfStudy: "Liên thông",
    yearGraduation: 2022,
    dateOfIssue: "2022-07-10",
    serialNumber: "SN002",
    referenceNumber: "REF002",
  },
  {
    no: 3,
    studentId: "SV003",
    name: "Lê Văn C",
    dob: "2000-01-10",
    faculty: "Luật",
    major: "Luật thương mại",
    degreeClassification: "Trung bình",
    modeOfStudy: "Tại chức",
    yearGraduation: 2023,
    dateOfIssue: "2023-09-01",
    serialNumber: "SN003",
    referenceNumber: "REF003",
  },
];
